apiVersion: types.federation.k8s.io/v1alpha1
kind: FederatedServiceAccount
metadata:
  name: test-serviceaccount
  namespace: test-namespace
spec:
  template:
    automountServiceAccountToken: true
  placement:
    clusterNames:
    - cluster1
    - cluster2
