apiVersion: types.federation.k8s.io/v1alpha1
kind: FederatedConfigMap
metadata:
  name: test-configmap
  namespace: test-namespace
spec:
  template:
    data:
      A: ala ma kota
  placement:
    clusterNames:
    - cluster1
    - cluster2
  overrides:
  - clusterName: cluster2
    clusterOverrides:
    - path: data
      value:
        foo: bar
