apiVersion: v1
kind: Secret
metadata:
  name: mongodb-users-secret
type: Opaque 
data:
  database-admin-password: Y2x5ZGU=
  database-name: cGFjbWFu
  database-password: cGlua3k=
  database-user: Ymxpbmt5
  keyfile-value: cjNkaDR0Cg==
