apiVersion: v1
kind: Namespace
metadata:
  name: test-namespace
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: operatorgroup
  namespace: test-namespace
spec:
  targetNamespaces:
  - test-namespace
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: test-namespace
  namespace: test-namespace
spec:
  channel: alpha
  name: federation
  source: operatorhubio-catalog
  sourceNamespace: olm
