apiVersion: scheduling.kubefed.k8s.io/v1alpha1
kind: ReplicaSchedulingPreference
metadata:
  name: reverse-words
spec:
  targetKind: FederatedDeployment
  totalReplicas: 80
  clusters:
    "*":
      weight: 1
    cluster2:
      maxReplicas: 20
      weight: 1
