apiVersion: v1
kind: List
metadata:
  name: mongodb-secret-list
items:
- apiVersion: v1
  kind: Secret
  metadata:
    name: mongodb-secret
    namespace: mongo
  type: Opaque 
  data:
    database-admin-password: Y2x5ZGU=
    database-name: cGFjbWFu
    database-password: cGlua3k=
    database-user: Ymxpbmt5
    keyfile-value: cjNkaDR0Cg==
- apiVersion: v1
  kind: Secret
  metadata:
    name: mongodb-ssl 
    namespace: mongo
  type: Opaque 
  data:
    mongodb.pem: mongodbpemhere
    ca.pem: capemhere
