apiVersion: v1
kind: List
items:
- apiVersion: types.federation.k8s.io/v1alpha1
  kind: FederatedSecret
  metadata:
    name: mongodb-secret
  spec:
    template:
      data:
        database-admin-password: Y2x5ZGU=
        database-name: cGFjbWFu
        database-password: cGlua3k=
        database-user: Ymxpbmt5
        keyfile-value: cjNkaDR0Cg==
      type: Opaque
    placement:
      clusterNames:
      - feddemocl1
      - feddemocl2
      - feddemocl3
- apiVersion: types.federation.k8s.io/v1alpha1
  kind: FederatedSecret
  metadata:
    name: mongodb-ssl
  spec:
    template:
      data:
        mongodb.pem: mongodbpemhere 
        ca.pem: capemhere
      type: Opaque
    placement:
      clusterNames:
      - feddemocl1
      - feddemocl2
      - feddemocl3
