apiVersion: v1
kind: List
items:
- apiVersion: types.kubefed.k8s.io/v1beta1
  kind: FederatedSecret
  metadata:
    name: mongodb-secret
  spec:
    template:
      data:
        database-admin-password: Y2x5ZGU=
        database-name: cGFjbWFu
        database-password: cGlua3k=
        database-user: Ymxpbmt5
        keyfile-value: cjNkaDR0Cg==
      type: Opaque
    placement:
      clusters:
      - name: feddemocl1
      - name: feddemocl2
      - name: feddemocl3
- apiVersion: types.kubefed.k8s.io/v1beta1
  kind: FederatedSecret
  metadata:
    name: mongodb-ssl
  spec:
    template:
      data:
        mongodb.pem: mongodbpemhere 
        ca.pem: capemhere
      type: Opaque
    placement:
      clusters:
      - name: feddemocl1
      - name: feddemocl2
      - name: feddemocl3
