apiVersion: types.kubefed.k8s.io/v1beta1
kind: FederatedPersistentVolumeClaim
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  template:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  placement:
    clusters:
    - name: feddemocl1
    - name: feddemocl2
    - name: feddemocl3
