apiVersion: operators.coreos.com/v1
kind: CatalogSourceConfig
metadata:
  name: installed-federation-kube-federation-system
  namespace: openshift-marketplace
spec:
  csDisplayName: Community Operators
  csPublisher: Community
  targetNamespace: kube-federation-system
  packages: kubefed-operator
