apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: federation
  namespace: changemeNS
spec:
  channel: alpha
  name: kubefed-operator
  startingCSV: kubefed-operator.v0.1.0
  source: installed-federation-changemeNS
  sourceNamespace: changemeNS
