apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: federation
  namespace: changemeNS
spec:
  channel: alpha
  name: federation
  startingCSV: federation.v0.0.10
  source: installed-federation-changemeNS
  sourceNamespace: changemeNS
