apiVersion: types.federation.k8s.io/v1alpha1
kind: FederatedSecret
metadata:
  name: mongodb-users-secret
spec:
  template:
    data:
      # clyde
      database-admin-password: Y2x5ZGU=
      # pacman
      database-name: cGFjbWFu
      # pinky
      database-password: cGlua3k=
      # blinky
      database-user: Ymxpbmt5
    type: Opaque
  placement:
    clusterNames:
    - feddemocl1
    - feddemocl2
    - feddemocl3
