apiVersion: types.federation.k8s.io/v1alpha1
kind: FederatedService
metadata:
  name: pacman
  labels:
    name: pacman
spec:
  template:
    metadata:
      labels:
        name: pacman
    spec:
      type: ClusterIP
      ports:
        - port: 80
          targetPort: 8080
          protocol: TCP
      selector:
        name: pacman
  placement:
    clusterNames:
    - feddemocl1
    - feddemocl2
    - feddemocl3
