apiVersion: types.kubefed.k8s.io/v1beta1
kind: FederatedService
metadata:
  name: pacman
  labels:
    name: pacman
spec:
  template:
    metadata:
      labels:
        name: pacman
    spec:
      type: ClusterIP
      ports:
        - port: 80
          targetPort: 8080
          protocol: TCP
      selector:
        name: pacman
  placement:
    clusters:
    - name: feddemocl1
    - name: feddemocl2
    - name: feddemocl3
