apiVersion: types.kubefed.k8s.io/v1beta1
kind: FederatedIngress
metadata:
  name: pacman
spec:
  template:
    spec:
      rules:
      - host: pacmanhosthere
        http:
          paths:
          - path: /
            backend:
              serviceName: pacman
              servicePort: 80
  placement:
    clusters:
    - name: feddemocl1
    - name: feddemocl2
    - name: feddemocl3
