apiVersion: types.federation.k8s.io/v1alpha1
kind: FederatedIngress
metadata:
  name: pacman
spec:
  template:
    spec:
      rules:
      - host: pacmanhosthere
        http:
          paths:
          - path: /
            backend:
              serviceName: pacman
              servicePort: 80
  placement:
    clusterNames:
    - feddemocl1
    - feddemocl2
    - feddemocl3
